language: node_js
node_js:
  - "6"
before_install:
- npm i -g npm
- npm i -g greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run build
after_script:
  - greenkeeper-lockfile-upload